### ISSUE TITLE
Shared Variable translation failing

### ISSUE THREAD

**Issue by lo-co** [NOAA-CSD/AOP#1]
AOP data for both the CRD and PAS is coming across as corrupt on the network.  See thread [here](https://forums.ni.com/t5/LabVIEW/Shared-Variable-bug-when-unflattening-class-from-string/td-p/3848556).
Seems to be an issue associated strictly with the MFC data from the Alicat's.

**Comment by nicholaslwagner** [comment]
One change that we made to AOP was removing the Alicat pressure controller. The pressure controller was unplugged, used elsewhere and never reinstalled on the AOP instrument. I bring this up because this error seem related to the Alicat data and it was a change that happened at a similar time to the labview upgrade.

**Comment by nicholaslwagner** [comment]
Is this error related to the UI executable not communicating with the server?

**Comment by lo-co** [comment]
OK...so I was able to get this to go away by setting diagram disable over the file writing.  Need this to work without doing that.

**Comment by lo-co** [comment]
Problem appears to be solved on the server side - can run the VI with the server running as an exe - but there still appears to be an issue with running the UI as an exe.

**Comment by lo-co** [comment]
So, the problem is that the data structures are not well defined at run time.  For whatever reason, they have to be explicitly defined _on the diagram_ - they can not just be included.  Fixed now.

**Comment by nicholaslwagner** [comment]
Thanks for looking into this. It a relief to have this issue put to rest.  I'll test is on the development computer and AMP field campaign computers
